# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Circuitscape
email: circuitscape@googlegroups.com
description: >- # this means to ignore newlines until "baseurl:"
    Circuitscape is an award-winning connectivity analysis software package which 
    borrows algorithms from electronic circuit theory to predict patterns of movement, 
    gene flow, and genetic differentiation among plant and animal populations 
    in heterogeneous landscapes. Circuitscape has rapidly become the most widely used 
    connectivity analysis package in the world. It is used by numerous state, federal, 
    and local agencies in the USA, and by government ministries and NGOs for conservation 
    planning on six continents. It routinely appears in journals like PNAS, 
    Nature Genetics, Ecology, Ecological Applications, Ecology Letters, Landscape Ecology, 
    Evolution, Heredity, Bioscience, Molecular Ecology, Conservation Biology, and many others. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  Circuitscape

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Header pages
header_pages: 
  - docs.md
  - downloads.md 
  - about.md 
  - linkage-mapper.md
  - pubs.md
  - authors.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
