name: Build and Deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1'
    - name: Build site
      run: julia -e '
            using Pkg; Pkg.activate("."); Pkg.instantiate();
            using Franklin;
            optimize(minify=false, prerender=false)'
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: __site
